import Head from "next/head";
import Image from "next/image";

import coffeeStoresData from "../data/coffee-stores.json";

import styles from "../styles/Home.module.css";

import Banner from "../components/Banner/Banner";
import Card from "../components/Card/Card";

const imgPlaceholder =
  "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80";

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log("hi banner button");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee stores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="hero"
          />
        </div>
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((store) => (
                <Card
                  key={store.fsq_id}
                  name={store.name}
                  imgUrl={store.imgUrl || imgPlaceholder}
                  href={`/coffee-store/${store.fsq_id}`}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const options = {
    method: "GET",
    headers: {
      Accept: "application/json",
      Authorization: "fsq3AS5cAI8DfiOJG3BwVrpH+Tx2+o/nXIkIasA8N0EexwA=",
    },
  };

  const response = await fetch(
    "https://api.foursquare.com/v3/places/search?query=coffee&limit=6",
    options
  );
  const data = await response.json();
  // .catch((err) => console.error(err));

  return {
    props: {
      coffeeStores: data.results,
    }, // will be passed to the page component as props
  };
}
